name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: supnobita/ssh-action@master
      with:
        host: 3.127.247.73
        username: ubuntu
        key: ${{ secrets.ADV_DEV_SECRET }}
        port: 22
        script: |
          cd code/
          rm -rf adv/
          git clone git@github.com:zunohan/adv.git
          cd adv
          docker build -t adv:$GITHUB_RUN_NUMBER .
          docker stop adv || echo "OK"
          docker rm adv || echo "OK"
          docker run --name adv -p 6969:6969 adv:$GITHUB_RUN_NUMBER
